name: Flask
run: |
  python3 -m pip install --upgrade pip
  pip install -r requirements.txt
  python3 -m pytest


    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Run Tests
      run: |
        python3 -m pytest